name: Gitleaks Secret Scan

on:
  push:
    branches: [ main ]      # Run on push to main
  pull_request:
    branches: [ main ]      # Run on PRs to main

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1    # Only fetch latest commit (no history)

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --no-git --report-format=json --report-path=gitleaks-report.json
